packages:
  - vendor/deepseek-harness/vendor/*
  - vendor/deepseek-harness/packages/*/*
  - vendor/deepseek-harness/native/system
  - vendor/deepseek-harness/native/system/packages/*
  - vendor/deepseek-harness/apps/*
  - devpackages/*
  - packages/*
  - apps/*

linkWorkspacePackages: true
hoistWorkspacePackages: true
autoInstallPeers: true

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@deepseek-ai/dsh-subprocess-local@file:vendor/deepseek-harness/packages/subprocess/subprocess-local": true
  "@google/genai": true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-ext: true
  koffi: true
  msgpackr-extract: true
  node-pty: true
  protobufjs: true

minimumReleaseAge: 0
