import type { CSSProps } from "@morlay/dsh-client-ui-primitives/client";

export const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 var(--dsh-composer-side-clearance) 8px",
    "&:has([data-composer-stats])": {
      paddingBottom: "4px",
    },
  },
  hero: {
    padding: "0 var(--dsh-composer-side-clearance)",
    "& [data-composer-input]": {
      minHeight: "52px",
    },
    "& [data-composer-placeholder]": {
      whiteSpace: "normal",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: "2",
      lineClamp: "2",
    },
  },
  notice: {
    width: "100%",
    maxWidth: "var(--dsh-composer-card-max-width)",
    marginBottom: "6px",
    padding: "4px 8px",
    borderRadius: "8px",
    background: "var(--dsw-alias-interactive-bg-hover)",
    color: "var(--dsw-alias-label-secondary)",
    fontSize: "12px",
    lineHeight: "18px",
  },
  card: {
    boxSizing: "border-box",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
    maxWidth: "var(--dsh-composer-card-max-width)",
    paddingTop: "8px",
    border: "0",
    "--dsw-elevation-stroke-color": "var(--dsw-alias-border-l2)",
    borderRadius: "22px",
    background: "var(--dsw-specific-input-major)",
    boxShadow: "var(--dsw-elevation-soft)",
    fontSize: "var(--dsh-content-font-size, 14px)",
    lineHeight: "calc(24px + var(--dsh-content-font-delta, 0px))",
    "--dsh-scrollbar-thumb": "var(--dsw-alias-scrollbar-bg-l2)",
    "--dsh-scrollbar-thumb-hover": "var(--dsw-alias-scrollbar-hover-l2)",
  },
  cardWorkspaceTrigger: {
    "--dsw-elevation-stroke-color": "transparent",
    cursor: "pointer",
    "&::after": {
      content: "''",
      position: "absolute",
      inset: "-1px",
      borderRadius: "22px",
      background: "var(--dsw-alias-border-l4)",
      transition: "background-color 100ms ease",
      WebkitMask:
        "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='100%25' height='100%25' fill='none' rx='22' ry='22' stroke='black' stroke-width='2' stroke-dasharray='4 4'/%3E%3C/svg%3E\")",
      mask: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='100%25' height='100%25' fill='none' rx='22' ry='22' stroke='black' stroke-width='2' stroke-dasharray='4 4'/%3E%3C/svg%3E\")",
      pointerEvents: "none",
    },
    "& :disabled": {
      pointerEvents: "none",
    },
    "&:hover::after": {
      background: "var(--dsw-alias-state-business-primary)",
    },
  },
  accessory: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 12px 0",
  },
  overlayAnchor: {
    position: "absolute",
    inset: "0 0 auto",
    height: "0",
  },
  scroll: {
    maxHeight: "var(--dsh-composer-text-max-height)",
    overflowY: "auto",
    marginRight: "4px",
    "&::-webkit-scrollbar-track": {
      marginTop: "8px",
    },
  },
  grow: {
    position: "relative",
  },
  pending: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    cornerShape: "round",
    background: "var(--dsw-alias-state-business-primary)",
    animation: "input-pending 1s ease-in-out infinite alternate",
  },
  input: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "4px 8px 0 14px",
    fontFamily: "var(--dsw-font-family)",
    fontSize: "inherit",
    lineHeight: "inherit",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "anywhere",
    outline: "none",
    color: "var(--dsw-alias-label-primary)",
    caretColor: "var(--dsw-alias-state-business-primary)",
    "& p": {
      margin: "0",
    },
    "& p:last-child::after": {
      content: "var(--dsh-composer-hint)",
      color: "var(--dsw-alias-label-caption)",
    },
    "&[data-composer-composing] p:last-child::after": {
      content: "none",
    },
    "&[data-composer-composing] + [data-composer-placeholder]": {
      visibility: "hidden",
    },
    "&[aria-haspopup='menu']": {
      cursor: "pointer",
    },
  },
  placeholder: {
    position: "absolute",
    inset: "4px 8px auto 14px",
    color: "var(--dsw-alias-label-caption)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    pointerEvents: "none",
    userSelect: "none",
  },
  inputDisabled: {
    color: "var(--dsw-alias-label-tertiary)",
    cursor: "not-allowed",
  },
  row: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "2px 8px 6px",
    minWidth: "0",
    containerType: "inline-size",
  },
  tools: {
    display: "flex",
    alignItems: "center",
    minWidth: "0",
    gap: "12px",
  },
  modes: {
    display: "flex",
    alignItems: "center",
    minWidth: "0",
    gap: "12px",
  },
  trailing: {
    display: "flex",
    alignItems: "center",
    minWidth: "0",
    flex: "none",
    marginLeft: "auto",
    gap: "12px",
  },
  add: {
    display: "grid",
    placeItems: "center",
    flex: "none",
    width: "28px",
    height: "28px",
    border: "none",
    borderRadius: "999px",
    cornerShape: "round",
    background: "var(--dsw-specific-selector)",
    color: "var(--dsw-alias-label-primary)",
    cursor: "pointer",
    "&:hover:not(:disabled)": {
      background: "var(--dsw-alias-interactive-bg-hover-solid)",
    },
    "&:disabled": {
      opacity: "0.5",
      cursor: "default",
    },
  },
  select: {
    maxWidth: "220px",
    height: "28px",
    padding: "0 20px 0 8px",
    border: "none",
    borderRadius: "8px",
    outline: "none",
    backgroundColor: "transparent",
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12' fill='none'%3E%3Cpath d='M3 4.5L6 7.5L9 4.5' stroke='%2381858C' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 4px center",
    backgroundSize: "12px 12px",
    color: "var(--dsw-alias-label-secondary)",
    fontSize: "13px",
    lineHeight: "20px",
    fontWeight: "500",
    whiteSpace: "nowrap",
    cursor: "pointer",
    appearance: "none",
    "&:hover:not(:disabled)": {
      backgroundColor: "var(--dsw-alias-interactive-bg-hover)",
    },
    "&:disabled": {
      opacity: "0.5",
      cursor: "default",
    },
  },
  primary: {
    display: "grid",
    placeItems: "center",
    flex: "none",
    width: "34px",
    height: "34px",
    border: "none",
    borderRadius: "999px",
    cornerShape: "round",
    background: "var(--dsw-alias-button-info-fill)",
    color: "#fff",
    cursor: "pointer",
    transition: "background-color 100ms ease",
    transform: "translateY(-2px)",
    "&:hover:not(:disabled)": {
      background: "var(--dsw-alias-button-info-hover)",
    },
    "&:disabled": {
      opacity: "0.4",
      cursor: "default",
    },
  },
  retry: {
    marginLeft: "8px",
    padding: "1px 8px",
    border: "1px solid currentColor",
    borderRadius: "4px",
    background: "transparent",
    color: "inherit",
    fontSize: "12px",
    cursor: "pointer",
  },
} satisfies Record<string, CSSProps>;

export const animations = {
  "input-pending": {
    from: {
      opacity: "0.35",
    },
    to: {
      opacity: "1",
    },
  },
} satisfies Record<string, Record<string, CSSProps>>;
