import type { CSSProps } from "@morlay/dsh-client-ui-primitives/client";

export const styles = {
  dock: {
    boxSizing: "border-box",
    flex: "none",
    width:
      "calc(\n    100% -\n    var(--dsh-composer-side-clearance) -\n    var(--dsh-composer-side-clearance) -\n    var(--dsh-composer-dock-inset) -\n    var(--dsh-composer-dock-inset)\n  )",
    maxWidth:
      "calc(\n    var(--dsh-composer-card-max-width) -\n    var(--dsh-composer-dock-inset) -\n    var(--dsh-composer-dock-inset)\n  )",
    margin: "0 auto calc(0px - var(--dsh-composer-stack-gap) - 3px)",
    padding: "0 var(--dsh-composer-dock-inset)",
  },
  panel: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    padding: "2px 0",
    borderRadius: "12px 12px 0 0",
    background: "var(--dsw-specific-tip)",
    "--dsh-scrollbar-thumb": "var(--dsw-alias-scrollbar-bg-l2)",
    "--dsh-scrollbar-thumb-hover": "var(--dsw-alias-scrollbar-hover-l2)",
    "&::after": {
      position: "absolute",
      inset: "0",
      border: "0.5px solid var(--dsw-alias-border-l1)",
      borderBottom: "none",
      borderRadius: "inherit",
      content: "''",
      pointerEvents: "none",
    },
  },
  header: {
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    width: "100%",
    height: "36px",
    padding: "4px 12px",
    border: "none",
    borderRadius: "8px",
    background: "transparent",
    color: "var(--dsw-alias-label-primary)",
    textAlign: "left",
    cursor: "pointer",
    "&:focus-visible": {
      outline: "2px solid var(--dsw-alias-label-tertiary)",
      outlineOffset: "-2px",
    },
    "&:disabled": {
      cursor: "default",
    },
  },
  lead: {
    display: "grid",
    flex: "none",
    placeItems: "center",
    color: "var(--dsw-alias-label-tertiary)",
  },
  count: {
    flex: "1 1 auto",
    minWidth: "0",
    fontFamily: "Inter, var(--dsw-font-family)",
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: "24px",
  },
  chevron: {
    display: "grid",
    flex: "none",
    placeItems: "center",
    width: "14px",
    height: "14px",
    color: "var(--dsw-alias-label-tertiary)",
  },
  list: {
    maxHeight: "180px",
    overflowY: "auto",
    margin: "0",
    padding: "0",
    listStyle: "none",
  },
  row: {
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    width: "100%",
    height: "36px",
    padding: "4px 5px 4px 12px",
    borderRadius: "8px",
    "& + [data-queue-row]": {
      boxShadow: "inset 0 1px 0 var(--dsw-alias-border-l1)",
    },
  },
  attachments: {
    display: "flex",
    flex: "none",
    gap: "4px",
    minWidth: "0",
    maxWidth: "55%",
    overflow: "hidden",
  },
  pendingRow: {
    "& [data-queue-attachments]": {
      flexShrink: "1",
    },
  },
  file: {
    display: "inline-flex",
    flex: "0 1 180px",
    alignItems: "center",
    gap: "4px",
    minWidth: "74px",
    height: "24px",
    padding: "0 6px",
    overflow: "hidden",
    border: "0.5px solid var(--dsw-alias-border-l1)",
    borderRadius: "6px",
    background: "var(--dsw-alias-bg-base)",
    boxSizing: "border-box",
  },
  fileIcon: {
    display: "inline-flex",
    flex: "none",
    width: "16px",
    height: "16px",
  },
  fileName: {
    minWidth: "0",
    overflow: "hidden",
    color: "var(--dsw-alias-label-primary-dimmed)",
    font: "var(--dsw-font-xs-13)",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileSize: {
    flex: "none",
    color: "var(--dsw-alias-label-tertiary)",
    fontSize: "10px",
    whiteSpace: "nowrap",
  },
  thumb: {
    width: "24px",
    height: "24px",
    border: "0.5px solid var(--dsw-alias-border-l1)",
    borderRadius: "4px",
    background: "var(--dsw-alias-bg-base)",
    objectFit: "cover",
  },
  preview: {
    display: "block",
    flex: "1 1 auto",
    minWidth: "0",
    font: "var(--dsw-font-xs-13)",
    fontFamily: "Inter, var(--dsw-font-family)",
    overflow: "hidden",
    color: "var(--dsw-alias-label-primary-dimmed)",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    wordBreak: "break-word",
    // 单行展示：队列行渲染的是原始 markdown，段落 / 列表 / 代码块这些块级结构各自换行
    // （36px 的行高装不下）。这里只把渲染出来的块级结构压成 inline 流，交给上面的
    // nowrap + ellipsis 裁成一行——队列行的数据与文本投影（queue-text.ts）不变。
    // 选择器带宿主属性是为了特异性高于官方 markdown 表的 `.markdown p` / `.markdown hr` 一类规则。
    "&[data-queue-preview] :is(p, div, ul, ol, li, h1, h2, h3, h4, h5, h6, blockquote, pre, hr, table, thead, tbody, tfoot, tr, td, th, img, figure, section)":
      {
        display: "inline",
        margin: "0",
        padding: "0",
        whiteSpace: "nowrap",
      },
  },
  actions: {
    display: "flex",
    flex: "none",
    alignItems: "center",
    gap: "10px",
  },
  status: {
    flex: "none",
    color: "var(--dsw-alias-label-tertiary)",
    font: "var(--dsw-font-xs-13)",
    whiteSpace: "nowrap",
  },
  action: {
    display: "grid",
    flex: "none",
    placeItems: "center",
    width: "28px",
    height: "28px",
    padding: "0",
    border: "none",
    borderRadius: "999px",
    cornerShape: "round",
    background: "transparent",
    color: "var(--dsw-alias-label-tertiary)",
    cursor: "pointer",
    "&:hover:not(:disabled)": {
      background: "var(--dsw-alias-interactive-bg-hover)",
    },
    "&:focus-visible": {
      outline: "2px solid var(--dsw-alias-label-tertiary)",
      outlineOffset: "-2px",
    },
    "&:disabled": {
      cursor: "default",
      opacity: "0.45",
    },
  },
} satisfies Record<string, CSSProps>;
