import type { CSSProps } from "@morlay/dsh-client-ui-primitives/client";

export const styles = {
  menu: {
    position: "absolute",
    bottom: "calc(100% + 4px)",
    left: "0",
    right: "0",
    zIndex: "100",
    boxSizing: "border-box",
    maxHeight: "400px",
    overflow: "hidden",
    "--dsh-scrollbar-thumb": "var(--dsw-alias-scrollbar-bg-l2)",
    "--dsh-scrollbar-thumb-hover": "var(--dsw-alias-scrollbar-hover-l2)",
    "--dsh-scrollbar-width": "10px",
    "--dsh-scrollbar-thumb-border": "3px",
    "--dsh-scrollbar-track-margin": "12px",
    padding: "4px",
    display: "flex",
    flexDirection: "column",
    border: "0",
    borderRadius: "20px",
    background: "var(--dsw-specific-menu)",
    "--dsw-elevation-stroke-color": "var(--dsw-alias-border-l1)",
    boxShadow: "var(--dsw-elevation-prominent)",
    "&[data-overflow-below]::after": {
      content: "''",
      position: "absolute",
      right: "14px",
      bottom: "4px",
      left: "4px",
      height: "16px",
      background: "linear-gradient(to bottom, transparent, var(--dsw-specific-menu))",
      pointerEvents: "none",
    },
  },
  viewport: {
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    overflowY: "auto",
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    minHeight: "40px",
    padding: "8px 10px",
    border: "none",
    borderRadius: "10px",
    background: "transparent",
    cursor: "pointer",
    fontSize: "14px",
    lineHeight: "22px",
    color: "var(--dsw-alias-label-primary)",
    textAlign: "left",
    "&[data-active] .drillHintText": {
      display: "inline-flex",
    },
    "&[data-active] .drillHint": {
      display: "inline-flex",
    },
  },
  itemActive: {
    background: "var(--dsw-alias-interactive-bg-hover)",
  },
  sectionTitle: {
    flex: "none",
    minHeight: "26px",
    padding: "6px 10px 2px",
    color: "var(--dsw-alias-label-tertiary)",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: "18px",
    "&:not(:first-child)": {
      marginTop: "4px",
    },
  },
  itemIcon: {
    display: "inline-flex",
    flex: "none",
    width: "16px",
    height: "16px",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--dsw-alias-label-tertiary)",
  },
  itemName: {
    flex: "none",
    maxWidth: "40%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemAlias: {
    flex: "none",
    maxWidth: "20%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--dsw-alias-label-tertiary)",
  },
  itemDescription: {
    flex: "1",
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "right",
    color: "var(--dsw-alias-label-tertiary)",
  },
  trailing: {
    flex: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    marginLeft: "auto",
  },
  drillHintText: {
    display: "none",
    color: "var(--dsw-alias-label-caption)",
    fontSize: "11px",
    lineHeight: "18px",
    whiteSpace: "nowrap",
  },
  drillHint: {
    display: "none",
    padding: "0 5px",
    borderRadius: "4px",
    background: "var(--dsw-alias-interactive-bg-hover)",
    color: "var(--dsw-alias-label-caption)",
    fontFamily: "inherit",
    fontSize: "11px",
    lineHeight: "18px",
  },
  drill: {
    flex: "none",
    display: "inline-grid",
    placeItems: "center",
    width: "20px",
    height: "20px",
    borderRadius: "4px",
    color: "var(--dsw-alias-label-caption)",
    "&:hover": {
      background: "var(--dsw-alias-interactive-bg-hover)",
      color: "var(--dsw-alias-label-primary)",
    },
  },
  groupTitle: {
    padding: "8px 10px",
    fontSize: "12px",
    lineHeight: "16px",
    color: "var(--dsw-alias-label-tertiary)",
  },
  skeletonRow: {
    display: "flex",
    alignItems: "center",
    boxSizing: "border-box",
    minHeight: "40px",
    padding: "8px 10px",
  },
  skeletonBar: {
    height: "20px",
    borderRadius: "4px",
    background: "var(--dsw-alias-bg-skeleton)",
    animation: "dsh-menu-skeleton 2s cubic-bezier(0.36, 0, 0.64, 1) infinite",
  },
  crumbs: {
    flex: "none",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "2px",
    padding: "4px 4px 6px",
    marginBottom: "2px",
    borderBottom: "0.5px solid var(--dsw-alias-border-l1)",
  },
  crumb: {
    flex: "0 1 auto",
    maxWidth: "40%",
    overflow: "hidden",
    padding: "2px 6px",
    border: "none",
    borderRadius: "6px",
    background: "transparent",
    color: "var(--dsw-alias-label-tertiary)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    lineHeight: "18px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "&:hover": {
      background: "var(--dsw-alias-interactive-bg-hover)",
      color: "var(--dsw-alias-label-primary)",
    },
  },
  crumbCurrent: {
    background: "transparent",
    color: "var(--dsw-alias-label-primary)",
    cursor: "default",
    "&:hover": {
      background: "transparent",
      color: "var(--dsw-alias-label-primary)",
      cursor: "default",
    },
  },
  crumbSeparator: {
    flex: "none",
    display: "inline-flex",
    color: "var(--dsw-alias-label-caption)",
  },
} satisfies Record<string, CSSProps>;

export const animations = {
  "dsh-menu-skeleton": {
    "0%": {
      opacity: "1",
    },
    "40%": {
      opacity: "0.6",
    },
    "80%, 100%": {
      opacity: "1",
    },
  },
} satisfies Record<string, Record<string, CSSProps>>;
